In [2]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (4.70.1)
Collecting protobuf (from kagglesdk<1.0,>=0.1.22->kagglehub)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (2025.8.3)
Requirement already satisfied: colorama in C:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Installing collected packages: protobuf, kagglesdk, kagglehub

   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ---------------------------------------- 0/3 [protobuf]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   ---------------------------------------- 3/3 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37 protobuf-7.36.2

In [1]:
import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
print(path)

c:\Users\mzama\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

C:\Users\mzama\.cache\kagglehub\datasets\mlg-ulb\creditcardfraud\versions\3

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/mzama/.cache/kagglehub/datasets/mlg-ulb/creditcardfraud/versions/3/creditcard.csv")

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Time,284807.0,9.481386e+04,47488.145955,0.000000,54201.500000,84692.000000,139320.500000,172792.000000
V1,284807.0,1.175161e-15,1.958696,-56.407510,-0.920373,0.018109,1.315642,2.454930
V2,284807.0,3.384974e-16,1.651309,-72.715728,-0.598550,0.065486,0.803724,22.057729
V3,284807.0,-1.379537e-15,1.516255,-48.325589,-0.890365,0.179846,1.027196,9.382558
V4,284807.0,2.094852e-15,1.415869,-5.683171,-0.848640,-0.019847,0.743341,16.875344
V5,284807.0,1.021879e-15,1.380247,-113.743307,-0.691597,-0.054336,0.611926,34.801666
V6,284807.0,1.494498e-15,1.332271,-26.160506,-0.768296,-0.274187,0.398565,73.301626
V7,284807.0,-5.620335e-16,1.237094,-43.557242,-0.554076,0.040103,0.570436,120.589494
V8,284807.0,1.149614e-16,1.194353,-73.216718,-0.208630,0.022358,0.327346,20.007208
V9,284807.0,-2.414189e-15,1.098632,-13.434066,-0.643098,-0.051429,0.597139,15.594995
V10,284807.0,2.238554e-15,1.088850,-24.588262,-0.535426,-0.092917,0.453923,23.745136
V11,284807.0,1.724421e-15,1.020713,-4.797473,-0.762494,-0.032757,0.739593,12.018913
V12,284807.0,-1.245415e-15,0.999201,-18.683715,-0.405571,0.140033,0.618238,7.848392
V13,284807.0,8.238900e-16,0.995274,-5.791881,-0.648539,-0.013568,0.662505,7.126883
V14,284807.0,1.213481e-15,0.958596,-19.214325,-0.425574,0.050601,0.493150,10.526766
V15,284807.0,4.866699e-15,0.915316,-4.498945,-0.582884,0.048072,0.648821,8.877742
V16,284807.0,1.436219e-15,0.876253,-14.129855,-0.468037,0.066413,0.523296,17.315112
V17,284807.0,-3.768179e-16,0.849337,-25.162799,-0.483748,-0.065676,0.399675,9.253526
V18,284807.0,9.707851e-16,0.838176,-9.498746,-0.498850,-0.003636,0.500807,5.041069
V19,284807.0,1.036249e-15,0.814041,-7.213527,-0.456299,0.003735,0.458949,5.591971
V20,284807.0,6.418678e-16,0.770925,-54.497720,-0.211721,-0.062481,0.133041,39.420904
V21,284807.0,1.628620e-16,0.734524,-34.830382,-0.228395,-0.029450,0.186377,27.202839
V22,284807.0,-3.576577e-16,0.725702,-10.933144,-0.542350,0.006782,0.528554,10.503090
V23,284807.0,2.618565e-16,0.624460,-44.807735,-0.161846,-0.011193,0.147642,22.528412
V24,284807.0,4.473914e-15,0.605647,-2.836627,-0.354586,0.040976,0.439527,4.584549
V25,284807.0,5.109395e-16,0.521278,-10.295397,-0.317145,0.016594,0.350716,7.519589
V26,284807.0,1.686100e-15,0.482227,-2.604551,-0.326984,-0.052139,0.240952,3.517346
V27,284807.0,-3.661401e-16,0.403632,-22.565679,-0.070840,0.001342,0.091045,31.612198
V28,284807.0,-1.227452e-16,0.330083,-15.430084,-0.052960,0.011244,0.078280,33.847808
Amount,284807.0,8.834962e+01,250.120109,0.000000,5.600000,22.000000,77.165000,25691.160000
Class,284807.0,1.727486e-03,0.041527,0.000000,0.000000,0.000000,0.000000,1.000000

In [7]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=['Time','Amount']
)

df.drop_duplicates(inplace=True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['Class'].value_counts(normalize=True)

Class
0    0.998333
1    0.001667
Name: proportion, dtype: float64

### Dataset Information:
- Supervised Learning dataset
- Classification
- Highly imbalanced
- No missing values
- Some duplicates but removed

### Now as the dataset is imbalanced we will use some strategies for handling it:
1. Class Weights
2. Oversampling - SMOTE

### As this is Classification Supervised learning Problem, we will use following algorithms:
1. Random Forest
2. Logistic Regression
3. Gradient Boosting
4. Extreme Gradient Boosting
5. K-Nearest Neighbors

### We will working on the combination for these all algorithms and strategies.

### Data Preparation

In [10]:
# Seperating the Columns

X = df.iloc[:, :-1]
y = df["Class"]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# Training vs Temporary

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size = 0.3,
    random_state = 42,
    stratify = y
)

In [13]:
# Validation vs Testing

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size = 0.50,
    random_state = 42,
    stratify = y_temp
)

In [14]:
print(X.shape, X_train.shape, X_val.shape, X_test.shape)
print(y.shape, y_train.shape, y_val.shape, y_test.shape)

(283726, 30) (198608, 30) (42559, 30) (42559, 30)
(283726,) (198608,) (42559,) (42559,)

### Defining the Cross Validation for Screening

In [15]:
from sklearn.model_selection import StratifiedKFold, cross_validate

In [16]:
cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

In [17]:
scoring = {
    "PR-AUC": "average_precision",
    "F1": "f1",
    "Precision": "precision",
    "Recall": "recall"
}

### RANDOM FOREST

In [18]:
from sklearn.pipeline import Pipeline

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
# Random Forest

rf = Pipeline([
    ("model", RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=1,
    ))
])

In [ ]:
rf_cv = cross_validate(
    rf,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
rf_cv

{'fit_time': array([262.71201205, 266.28354478, 208.30588031]),
 'score_time': array([2.22889638, 1.60635042, 1.7634604 ]),
 'test_PR-AUC': array([0.83105117, 0.82973389, 0.83756558]),
 'test_F1': array([0.82926829, 0.85148515, 0.87437186]),
 'test_Precision': array([0.89473684, 0.94505495, 0.97752809]),
 'test_Recall': array([0.77272727, 0.77477477, 0.79090909])}

In [ ]:
rf_cv_results = pd.DataFrame([{
    "Model": "Random Forest",
    "PR-AUC Mean": rf_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": rf_cv["test_PR-AUC"].std(),
    "F1 Mean": rf_cv["test_F1"].mean(),
    "F1 Std": rf_cv["test_F1"].std(),
    "Precision Mean": rf_cv['test_Precision'].mean(),
    "Precision Std": rf_cv['test_Precision'].std(),
    "Recall Mean": rf_cv['test_Recall'].mean(),
    "Recall Std": rf_cv['test_Recall'].std()
}])

In [ ]:
results = rf_cv_results
results

,Model,PR-AUC Mean,PR-AUC Std,F1 Mean,F1 Std,Precision Mean,Precision Std,Recall Mean,Recall Std
0,Random Forest,0.832784,0.003424,0.851708,0.018414,0.939107,0.03406,0.77947,0.008131

### We calculate mean for `how good the model performs` and std for `how consistent is the model performance` ?

In [ ]:
# Random Forest with Class Weights adjusted

rf_cw = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

In [ ]:
rf_cw_cv = cross_validate(
    rf_cw,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
rf_cw_cv

{'fit_time': array([153.81481218, 159.00318265,  74.53839445]),
 'score_time': array([1.7529068 , 1.4257884 , 1.29693556]),
 'test_PR-AUC': array([0.83682021, 0.80558744, 0.84200666]),
 'test_F1': array([0.81818182, 0.84422111, 0.84536082]),
 'test_Precision': array([0.92045455, 0.95454545, 0.97619048]),
 'test_Recall': array([0.73636364, 0.75675676, 0.74545455])}

In [ ]:
rf_cw_cv_scores = pd.DataFrame([{
    "Model": "Random Forest With Class Weights",
    "PR-AUC Mean": rf_cw_cv["test_PR-AUC"].mean(),
    "PR-AUC Std": rf_cw_cv["test_PR-AUC"].std(),
    "F1 Mean": rf_cw_cv['test_F1'].mean(),
    "F1 Std": rf_cw_cv['test_F1'].std(),
    "Precision Mean": rf_cw_cv['test_Precision'].mean(),
    "Precision Std": rf_cw_cv['test_Precision'].std(),
    "Recall Mean": rf_cw_cv['test_Recall'].mean(),
    "Recall Std": rf_cw_cv['test_Recall'].std()
}])

In [ ]:
rf_cw_cv_scores

,Model,PR-AUC Mean,PR-AUC Std,F1 Mean,F1 Std,Precision Mean,Precision Std,Recall Mean,Recall Std
0,Random Forest With Class Weights,0.828138,0.016086,0.835921,0.012552,0.950397,0.022942,0.746192,0.008342

In [ ]:
results = pd.concat([results, rf_cw_cv_scores], ignore_index=True)
results

,Model,PR-AUC Mean,PR-AUC Std,F1 Mean,F1 Std,Precision Mean,Precision Std,Recall Mean,Recall Std
0,Random Forest,0.832784,0.003424,0.851708,0.018414,0.939107,0.034060,0.779470,0.008131
1,Random Forest With Class Weights,0.828138,0.016086,0.835921,0.012552,0.950397,0.022942,0.746192,0.008342

### Whenever Resampling is to be done, we use the pipeline from the Imblearn library which is for imbalanced datasets. This is because it applies the sampling technique to the training data but not on the testing data.

In [ ]:
# Random Forest with SMOTE

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [ ]:
rf_smote = Pipeline([
    ("smote", SMOTE(random_state=42)),
    ("model", RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ))
])

In [ ]:
rf_smote_cv = cross_validate(
    rf_smote,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

KeyboardInterrupt:

In [ ]:
rf_smote_cv_scores = pd.DataFrame([{
    "Model": "Random Forest With Smote",
    "PR-AUC Mean": rf_smote_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": rf_smote_cv['test_PR-AUC'].std(),
    "F1 Mean": rf_smote_cv['test_F1'].mean(),
    "F1 Std": rf_smote_cv['test_F1'].std(),
    "Precision Mean": rf_smote_cv['test_F1'].mean(),
    "Precision Std": rf_smote_cv['test_F1'].std(),
    "Recall Mean": rf_smote_cv['test_Recall'].mean(),
    "Recall Std": rf_smote_cv['test_Recall'].std()
}])

In [ ]:
rf_smote_cv_scores

In [ ]:
results = pd.concat([results, rf_smote_cv_scores], ignore_index=True)
results

### LOGISTIC REGRESSION

- As Logistic Regression is `Gradient Based model` we will be having a scaler for its application.

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

In [ ]:
lr_cv = cross_validate(
    lr,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
lr_cv_scores = pd.DataFrame([{
    "Model": "Logistic Regression",
    "PR-AUC Mean": lr_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": lr_cv['test_PR-AUC'].std(),
    "F1 Mean": lr_cv['test_F1'].mean(),
    "F1 Std": lr_cv['test_F1'].std(),
    "Precision Mean": lr_cv['test_Precision'].mean(),
    "Precision Std": lr_cv['test_Precision'].std(),
    "Recall Mean": lr_cv['test_Recall'].mean(),
    "Recall Std": lr_cv['test_Recall'].std(),
}])

lr_cv_scores

In [ ]:
results = pd.concat([results, lr_cv_scores], ignore_index=True)
results

In [ ]:
# Logistic Regression with Class Weights

lr_cw = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

In [ ]:
lr_cw_cv = cross_validate(
    lr_cw,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
lr_cw_cv_scores = pd.DataFrame([{
    "Model": "Logistic Regression with Class Weights",
    "PR-AUC Mean": lr_cw_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": lr_cw_cv['test_PR-AUC'].std(),
    "F1 Mean": lr_cw_cv['test_F1'].mean(),
    "F1 Std": lr_cw_cv['test_F1'].std(),
    "Precision Mean": lr_cw_cv['test_Precision'].mean(),
    "Precision Std": lr_cw_cv['test_Precision'].std(),
    "Recall Mean": lr_cw_cv['test_Recall'].mean(),
    "Recall Std": lr_cw_cv['test_Recall'].std(),
}])

lr_cw_cv_scores

In [ ]:
results = pd.concat([results, lr_cw_cv_scores], ignore_index=True)

results

In [ ]:
# Logistic Regression with SMOTE

from imblearn.pipeline import Pipeline

lr_smote = Pipeline([
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=42)),
    ("model", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

In [ ]:
lr_smote_cv = cross_validate(
    lr_smote,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
lr_smote_cv_scores = pd.DataFrame([{
    "Model": "Logistic Regression with SMOTE",
    "PR-AUC Mean": lr_smote_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": lr_smote_cv['test_PR-AUC'].std(),
    "F1 Mean": lr_smote_cv['test_PR-AUC'].mean(),
    "F1 Std": lr_smote_cv['test_PR-AUC'].std(),
    "Precision Mean": lr_smote_cv['test_Precision'].mean(),
    "Precision Std": lr_smote_cv['test_Precision'].std(),
    "Recall Mean": lr_smote_cv['test_Recall'].mean(),
    "Recall Std": lr_smote_cv['test_Recall'].std()
}])

lr_smote_cv_scores

Random Forest took so much time but Logistic Regression is so much fast

In [ ]:
results = pd.concat([results, lr_smote_cv_scores], ignore_index=True)

results

### GRADIENT BOOSTING

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gb = Pipeline([
    ("model", GradientBoostingClassifier(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=3,
        random_state=42

    ))
])

In [ ]:
gb_cv = cross_validate(
    gb,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
gb_cv_scores = pd.DataFrame([{
    "Model": "Gradient Boosting",
    "PR-AUC Mean": gb_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": gb_cv['test_PR-AUC'].std(),
    "F1 Mean": gb_cv['test_F1'].mean(),
    "F1 Std": gb_cv['test_F1'].std(),
    "Precision Mean": gb_cv['test_Precision'].mean(),
    "Precision Std": gb_cv['test_Precision'].std(),
    "Recall Mean": gb_cv['test_Recall'].mean(),
    "Recall Std": gb_cv['test_Recall'].std()
}])

gb_cv_scores

In [ ]:
results = pd.concat([results, gb_cv_scores], ignore_index=True)

In [ ]:
results

### Gradient Boosting Does not have inbuilt handling for class weights so going to `SMOTE` directly.

In [ ]:
# Gradient Boosting With Smote

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

In [ ]:
gb_smote = Pipeline([
    ("smote", SMOTE(random_state = 42)),
    ("model", GradientBoostingClassifier(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42,
        max_depth=3
    ))
])

In [ ]:
gb_smote_cv = cross_validate(
    gb_smote,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
gb_smote_cv_scores = pd.DataFrame([{
    "Model": "Gradient Boosting with SMOTE",
    "PR-AUC Mean": gb_smote_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": gb_smote_cv['test_PR-AUC'].std(),
    "F1 Mean": gb_smote_cv['test_F1'].mean(),
    "F1 Std": gb_smote_cv['test_F1'].std(),
    "Precision Mean": gb_smote_cv['test_Precision'].mean(),
    "Precision Std": gb_smote_cv['test_Precision'].std(),
    "Recall Mean": gb_smote_cv['test_Recall'].mean(),
    "Recall Std": gb_smote_cv['test_Recall'].std(),
}])

gb_smote_cv_scores

In [ ]:
from IPython.display import Audio, display
import numpy as np

# Generate a short beep
sample_rate = 44100
duration = 5.0
frequency = 1000

t = np.linspace(0, duration, int(sample_rate * duration), False)
beep = np.sin(2 * np.pi * frequency * t)

display(Audio(beep, rate=sample_rate, autoplay=True))

In [ ]:
results = pd.concat([results, gb_smote_cv_scores], ignore_index=True)

In [ ]:
results

### K-Nearest Neighbors

- We won't be using the class weights because KNN Classifier doesn't have any class_weight parameter.

In [ ]:
# KNN No Balancing

# Now, KNN is a distance based algorithm so we will be using Scaler.

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [ ]:
knn = Pipeline([
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier(
        n_neighbors=5,
        n_jobs=-1
    ))
])

In [ ]:
knn_cv = cross_validate(
    knn,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

display(Audio(beep, rate=sample_rate, autoplay=True))

In [ ]:
knn_cv_scores = pd.DataFrame([{
    "Model": "K Nearest Neighbors",
    "PR-AUC Mean": knn_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": knn_cv['test_PR-AUC'].std(),
    "F1 Mean": knn_cv['test_F1'].mean(),
    "F1 Std": knn_cv['test_F1'].std(),
    "Precision Mean": knn_cv['test_Precision'].mean(),
    "Precision Std": knn_cv['test_Precision'].std(),
    "Recall Mean": knn_cv['test_Recall'].mean(),
    "Recall Std": knn_cv['test_Recall'].std(),
}])

knn_cv_scores

In [ ]:
results = pd.concat([results, knn_cv_scores], ignore_index=True)

In [ ]:
results

In [ ]:
# KNN With SMOTE

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

In [ ]:
knn_smote = Pipeline([
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=42)),
    ("model", KNeighborsClassifier(
        n_neighbors=5,
        n_jobs=-1
    ))
])

In [ ]:
knn_smote_cv = cross_validate(
    knn_smote,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
knn_smote_cv_scores = pd.DataFrame([{
    "Model": "K Nearest Neighbors With SMOTE",
    "PR-AUC Mean": knn_smote_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": knn_smote_cv['test_PR-AUC'].std(),
    "F1 Mean": knn_smote_cv['test_F1'].mean(),
    "F1 Std": knn_smote_cv['test_F1'].std(),
    "Precision Mean": knn_smote_cv['test_Precision'].mean(),
    "Precision Std": knn_smote_cv['test_Precision'].std(),
    "Recall Mean": knn_smote_cv['test_Recall'].mean(),
    "Recall Std": knn_smote_cv['test_Recall'].std(),
}])

knn_smote_cv_scores

In [ ]:
display(Audio(beep, rate=sample_rate, autoplay=True))

In [ ]:
results = pd.concat([results, knn_smote_cv_scores], ignore_index=True)
results

### XGBOOST

In [ ]:
# XGBoost No sampling

from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier

xgb = Pipeline([
    ("model", XGBClassifier(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=3,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    )),
])

In [ ]:
xgb_cv = cross_validate(
    xgb,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
xgb_cv_scores = pd.DataFrame([{
    "Model": "XG Boosting",
    "PR-AUC Mean": xgb_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": xgb_cv['test_PR-AUC'].std(),
    "F1 Mean": xgb_cv['test_F1'].mean(),
    "F1 Std": xgb_cv['test_F1'].std(),
    "Precision Mean": xgb_cv['test_Precision'].mean(),
    "Precision Std": xgb_cv['test_Precision'].std(),
    "Recall Mean": xgb_cv['test_Recall'].mean(),
    "Recall Std": xgb_cv['test_Recall'].std(),
}])

xgb_cv_scores

In [ ]:
display(Audio(beep, rate=sample_rate, autoplay=True))

In [ ]:
results = pd.concat([results, xgb_cv_scores], ignore_index=True)
results

In [ ]:
# XGB With SMOTE

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

xgb_smote = Pipeline([
    ("smote", SMOTE(random_state=42)),
    ("model", XGBClassifier(
        n_estimators=100,
        max_depth=3,
        learning_rate=0.1,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1
    ))
])

In [ ]:
xgb_smote_cv = cross_validate(
    xgb_smote,
    X_train,
    y_train,
    cv=cv,
    scoring=scoring,
    n_jobs=-1
)

In [ ]:
xgb_smote_cv_scores = pd.DataFrame([{
    "Model": "XG Boosting With SMOTE",
    "PR-AUC Mean": xgb_smote_cv['test_PR-AUC'].mean(),
    "PR-AUC Std": xgb_smote_cv['test_PR-AUC'].std(),
    "F1 Mean": xgb_smote_cv['test_F1'].mean(),
    "F1 Std": xgb_smote_cv['test_F1'].std(),
    "Precision Mean": xgb_smote_cv['test_Precision'].mean(),
    "Precision Std": xgb_smote_cv['test_Precision'].std(),
    "Recall Mean": xgb_smote_cv['test_Recall'].mean(),
    "Recall Std": xgb_smote_cv['test_Recall'].std(),
}])

xgb_smote_cv_scores

In [ ]:
results = pd.concat([results, xgb_smote_cv_scores], ignore_index=True)
results.sort_values(by='PR-AUC Mean', ascending=False)

- Screening is Complete. Now we will move to the model fiteration.
- For Fraud Detection we will look at Precision,Recall,F1 and PR-AUC in the same order.

### Model Fitering:
1. XGBoost
2. Random Forest with SMOTE
3. Random Forest
4. Random Forest with weights
5. XGBoost with SMOTE

### HYPERPARAMETER TUNING

1. Random Forest

In [22]:
rf_param_grid = {
    "model__n_estimators": [200,300],
    "model__max_depth": [None, 10, 20]
}

In [23]:
from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(
    estimator=rf,
    param_grid=rf_param_grid,
    scoring="average_precision",
    cv=5,
    n_jobs=-1,
    verbose=5
)

In [24]:
rf_grid.fit(X_train, y_train)

print("RF Best Parameters:", rf_grid.best_params_)
print("RF Best CV PR-AUC:", rf_grid.best_score_)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

KeyboardInterrupt: